service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        type: request
        functionArn: arn:aws:lambda:us-east-1:059551633106:function:authorization-service-dev-basicAuthorizer
  environment:
    BUCKET_NAME: import-uploaded-bucket
    SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/059551633106/CatalogItemsQueue
    SQS_QUEUE_NAME: CatalogItemsQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
        - s3:CopyObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource: 'arn:aws:sqs:${self:provider.region}:${aws:accountId}:CatalogItemsQueue'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: GET
          authorizer:
            name: basicAuthorizer
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: uploaded/
            - suffix: .csv
